# Generated by Django 5.0 on 2023-12-27 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('regionid', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=10000)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'eve_api_region',
            },
        ),
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('constellationid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_api.region')),
            ],
            options={
                'db_table': 'eve_api_constellation',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('system_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('security_class', models.CharField(blank=True, max_length=2, null=True)),
                ('security_status', models.FloatField(blank=True, null=True)),
                ('constellation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eve_api.constellation')),
            ],
            options={
                'db_table': 'eve_api_system',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_api.system')),
            ],
            options={
                'db_table': 'eve_api_station',
            },
        ),
        migrations.CreateModel(
            name='Stargate',
            fields=[
                ('stargate_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_api.system')),
            ],
            options={
                'db_table': 'eve_api_stargate',
            },
        ),
    ]
