# Generated by Django 5.0 on 2023-12-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('regionid', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=10000)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
    ]
