# Generated by Django 5.0 on 2023-12-27 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='_danger_level',
            field=models.FloatField(db_column='danger_level', default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1680)]),
        ),
        migrations.AddField(
            model_name='system',
            name='days_researched',
            field=models.PositiveIntegerField(db_column='days_researched', default=0),
        ),
    ]
