# Generated by Django 5.0 on 2023-12-21 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('constellationid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_api.region')),
            ],
        ),
    ]
