# Generated by Django 5.0 on 2023-12-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_api', '0002_constellation'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('constellation_id', models.IntegerField(blank=True, null=True)),
                ('system_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('security_class', models.CharField(blank=True, max_length=2, null=True)),
                ('security_status', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
