# Generated by Django 5.0 on 2024-01-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eve_api', '0003_system_range_of_danger_level'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='system',
            name='range_of_danger_level',
        ),
        migrations.RemoveField(
            model_name='system',
            name='_danger_level',
        ),
        migrations.RemoveField(
            model_name='system',
            name='days_researched',
        ),
    ]
