# Generated by Django 5.0 on 2023-12-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eve_api', '0003_system'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='constellation_id',
            new_name='constellation',
        ),
    ]
