# Generated by Django 5.0 on 2024-01-09 11:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_api', '0004_remove_system_range_of_danger_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangerRating',
            fields=[
                ('rating_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('system_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_api.system')),
            ],
        ),
    ]
