# Generated by Django 5.0 on 2023-12-22 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_api', '0004_rename_constellation_id_system_constellation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='constellation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eve_api.constellation'),
        ),
    ]
