# Generated by Django 5.0 on 2024-01-09 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_api', '0006_rename_system_id_dangerrating_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dangerrating',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danger_rating_units', to='eve_api.system'),
        ),
    ]
