# Generated by Django 5.0 on 2023-12-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_api', '0006_stargate_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stargate',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
