# Generated by Django 5.0.1 on 2024-01-20 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eve_api', '0007_alter_dangerrating_system'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dangerrating',
            table='eve_api_dangerrating',
        ),
    ]
