# Generated by Django 5.0 on 2023-12-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_api', '0007_alter_stargate_name_alter_station_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
