# Generated by Django 5.0 on 2023-12-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_api', '0008_alter_station_station_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
