# Generated by Django 5.0 on 2023-12-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eve_api', '0009_alter_station_station_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Station',
        ),
    ]
