# Generated by Django 5.0 on 2023-12-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eve_api', '0013_station'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Station',
        ),
    ]
